### ISSUE TITLE
Error: The site seems to be down.

### ISSUE THREAD

**Issue by Ragosh** [mdn/mdn-http-observatory#118] opened 2024-11-19 10:38 UTC
### What information was incorrect, unhelpful, or incomplete?

The site is not down. I can access the website and I couldn't find any html errors.

### What did you expect to see?

I expected to get the report. :)

### Do you have any supporting links, references, or citations?

Website I tried to scan: https://avu.de/

### Do you have anything more you want to share?

What I did:
1. Open https://developer.mozilla.org/en-US/observatory
2. Enter the website https://avu.de/
3. "Error: The site seems to be down." is shown.

I also tried opening the following links:
https://developer.mozilla.org/en-US/observatory/analyze?host=www.avu.de
https://developer.mozilla.org/en-US/observatory/analyze?host=avu.de
https://developer.mozilla.org/en-US/observatory/analyze?host=https://avu.de/

**Comment by euneuber** [comment] 2024-11-28 20:52
Any update on this? I also have a site that is incorrectly displayed as ‘down’.

**Comment by OSnuszka** [comment] 2024-11-29 15:50
Same for me, some pages are available to scan without VPN, but with VPN I receive `Error: The site seems to be down.`

**Comment by caugner** [comment] 2024-12-02 09:01
I can reproduce the issue with this domain from the command line (without VPN):

```
% npx @mdn/mdn-http-observatory avu.de
{"error":"The site seems to be down."}
```

**Comment by euneuber** [comment] 2024-12-02 18:11
When using `curl` with the same `Accept` header as the connect function in the scan command, I get:

```
curl: (60) SSL peer certificate or SSH remote key was not OK
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the webpage mentioned above.
```

Maybe it is certificate related?

PS: Issuer of ther certificate is "GlobalSign nv-sa" common name is "AlphaSSL CA - SHA256 - G4"

**Comment by argl** [comment] 2024-12-04 14:53
Please check again, the fix has been deployed just now.

**Comment by Ragosh** [comment] 2024-12-04 15:19
Awesome, it's working now. Thanks a lot!

**Closed** 2024-12-04 15:20 UTC
Labels: bug

**Comment by euneuber** [comment] 2024-12-08 17:24
Thank you!
